export type HealthResponse = { status: string; database?: boolean }
export type Draft = { id: string; from_alias: string | null; to_address: string | null; cc: string | null; bcc: string | null; subject: string; body: string; body_html: string | null; updated_at: string }
export type DraftListResponse = { drafts: Draft[] }
export type CreateAccountResponse = { account_code: string; existing?: boolean }
export type LoginResponse = { access_token: string; token_type: string; expires_in: number }
export type Account = { account_id: string; created_at: string; primary_alias: string | null; domain: string | null; plan: "free" | "pro" | "cipher"; pro_until: string | null; can_send: boolean; can_use_secure_link?: boolean }
export type BillingStatus = { plan: "free" | "pro" | "cipher"; subscription_plan?: "free" | "pro" | "cipher"; pro_until: string | null; can_send: boolean; can_block_senders?: boolean; can_share_inbox?: boolean; can_use_custom_domains?: boolean; can_use_api?: boolean; can_send_html?: boolean; can_use_secure_link?: boolean; alias_count?: number; max_aliases?: number | null; billing_enabled: boolean; beta_features_enabled?: boolean; pending_invoice: BillingInvoice | null }
export type BillingInvoice = { invoice_id: string; plan: string; gateway: "monero" | "nowpayments"; status: string; expires_at: string; amount_xmr?: string; payment_id?: string; address?: string; integrated_address?: string | null; payment_uri?: string; amount_usd?: string; pay_address?: string; pay_amount?: string; pay_currency?: string }
export type BillingVerifyResponse = BillingStatus & { verification?: string; message?: string }
export type Attachment = { id: string; filename: string; content_type: string; size: number }
export type SendMessageAttachment = { filename: string; content_type: string; content_base64: string }
export type SendMessageRequest = { from_alias: string; to: string; cc?: string[] | null; bcc?: string[] | null; subject: string; body: string; body_html?: string | null; in_reply_to?: string | null; references?: string | null; secure_link?: boolean; secure_max_views?: number; secure_expires_hours?: number; secure_password?: string | null; attachments?: SendMessageAttachment[] | null }
export type OnboardingCompleteResponse = { primary_alias: string; domain: string; aliases_created: number; messages_seeded: number }
export type Alias = { id: string; handle: string; local_part: string; domain: string; label: string; icon: string; unread: number; is_burned: boolean; expires_at: string | null; burn_at?: string | null; notes?: string | null; shared?: boolean; is_owner?: boolean; permissions?: string[] }
export type AliasShare = { id: string; alias_id: string; alias_handle: string; owner_account_id: string; grantee_account_id: string | null; invite_token: string; permissions: string[]; status: string; created_at: string; accepted_at: string | null; invite_path: string }
export type AliasShareListResponse = { shares: AliasShare[] }
export type AliasListResponse = { aliases: Alias[] }
export type AliasAvailabilityResponse = { available: boolean; local_part: string; domain: string; reason: string | null }
export type Message = { id: string; alias: string; from: string; sender_name?: string | null; envelope_sender?: string | null; subject: string; preview: string; body: string; body_html?: string | null; received_at: string; unread: boolean; kind: string; starred: boolean; archived: boolean; deleted?: boolean; delivery_status?: "pending" | "sent" | "failed" | null; snoozed_until?: string | null; has_attachments?: boolean; direction?: "inbound" | "sent"; to?: string | null; message_id_header?: string | null; references_header?: string | null; attachments?: Attachment[] }
export type BlockedSender = { id: string; address: string; created_at: string }
export type BlockedSenderListResponse = { blocked_senders: BlockedSender[] }
export type AccountSettings = { message_retention_days: number | null; notification_privacy: "full" | "hide_subject" | "silent"; list_density: "comfortable" | "compact"; session_count: number; alias_share_count: number; domain_share_count: number; message_count: number; alias_count: number; blocked_sender_count: number }
export type BulkMessageRequest = { message_ids: string[]; read?: boolean; starred?: boolean; archived?: boolean; delete?: boolean; restore?: boolean }
export type MessageListResponse = { messages: Message[]; total: number }
export type CustomDomain = { id: string; domain: string; status: string; verification_token: string; added_at: string; is_builtin: boolean; is_shared?: boolean; is_owner?: boolean; dkim_selector?: string; checks?: { verify_txt: boolean; mx: boolean; spf: boolean; dkim: boolean; dmarc?: boolean } | null; dns_records?: { key: string; type: string; host: string; value: string; purpose: string; priority?: string | null; required?: boolean; verified?: boolean | null }[] | null }
export type DomainListResponse = { domains: CustomDomain[]; builtin_domains: string[] }
